## ....

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("TFT_Champion_CurrentVersion.csv")

In [3]:
df.head()

,name,cost,health,defense,attack,attack_range,speed_of_attack,dps,skill_name,skill_cost,origin,class
0,gangplank,5,1000,30,60,1,1.00,60,gangplank_orbitalstrike,100/175,Space Pirate,"['Mercenary', 'Demolitionist']"
1,graves,1,650,35,55,1,0.55,30,graves_smokegrenade,50/80,Space Pirate,['Blaster']
2,neeko,3,800,35,50,2,0.65,33,neeko_popblossom,75/150,Star Guardian,['Protector']
3,darius,2,750,35,60,1,0.65,39,darius_spacepirateguillotine,0/60,Space Pirate,['Mana-Reaver']
4,rakan,2,600,35,45,2,0.70,32,rakan_grandentrance,50/100,Celestial,['Protector']

In [19]:
df.groupby("name")["attack"].sum().sort_values(ascending = False)

name
jhin           90
irelia         70
jinx           70
shaco          70
chogath        70
malphite       70
fizz           60
jayce          60
missfortune    60
gangplank      60
xerath         60
kayle          60
ezreal         60
ekko           60
darius         60
xinzhao        60
shen           60
ashe           60
vi             60
xayah          55
mordekaiser    55
masteryi       55
graves         55
blitzcrank     55
poppy          50
neeko          50
rumble         50
karma          50
thresh         50
wukong         50
lucian         50
leona          50
khazix         50
kassadin       50
kaisa          50
jarvaniv       50
yasuo          50
syndra         45
velkoz         45
ahri           45
lulu           45
soraka         45
rakan          45
fiora          45
caitlyn        45
twistedfate    40
sona           40
lux            40
annie          40
ziggs          40
zoe            40
aurelionsol    10
Name: attack, dtype: int64